# config/_default/languages.es.toml

languageCode = "en"
languageName = "English"
weight = 2

title = "mariomenjr.com"

[params]
  isoCode = "en"
  displayName = "ðŸ‡ºðŸ‡¸"

[author]
  name = "Mario MenjÃ­var"
  image = "img/author.jpg"
  headline = "Curiosity-driven human. Computer scientist. Immigrant."
  bio = "Curiosity-driven human. Computer scientist. Immigrant."
  links = [
    { linkedin = "https://linkedin.com/in/mariomenjr" },
    { email = "mailto:mariomenjr@gmail.com" },
    { github = "https://github.com/mariomenjr" },
    { youtube = "https://youtube.com/mariomenjr" },
    { twitter = "https://twitter.com/mariomenjr" },
  ]