# config/_default/menus.en.toml

[[main]]
  name = "blog"
  pageRef = "blog"
  weight = 10

# [[main]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 20

[[main]]
  name = "sobre m√≠"
  pageRef = "about"
  weight = 20

# [[main]]
#   name = "linkedin"
#   url = "https://linkedin.com/in/mariomenjr"
#   weight = 30
#   [main.params]
#     icon = "linkedin"
#     showName = false
#     target = "_blank"

# [[main]]
#   identifier = "search"
#   weight = 40
#   [main.params]
#     action = "search"
#     icon = "search"

# [[footer]]
#   name = "Resume"
#   url = "https://go.mariomenjr.com/resume"